name: Auto Update Subscription

on:
  schedule:
    - cron: '0 */6 * * *' # اجرای خودکار هر ۶ ساعت یک‌بار
  workflow_dispatch: # امکان اجرای دستی از تب Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Processing Script
        run: python process.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sub.txt
          git commit -m "Auto update sub configs" || exit 0
          git push
